<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit60cbf2b3c2b2d7a68dec5402121b4e45
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit60cbf2b3c2b2d7a68dec5402121b4e45::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit60cbf2b3c2b2d7a68dec5402121b4e45::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
